-- seed.sql (120 sample FAQ entries for an e-commerce style site)
INSERT INTO faq (question, answer) VALUES
('how do i create an account', 'Click on Sign Up and fill your name, email, and password to create an account.'),
('how can i log in to my account', 'Go to the login page and enter your registered email and password.'),
('i forgot my password what should i do', 'Click on Forgot Password and follow the instructions to reset it.'),
('how can i change my password', 'Visit account settings and select Change Password.'),
('can i update my email address', 'Yes, you can update it from your profile settings under contact information.'),
('how do i delete my account', 'Please contact support to permanently delete your account.'),
('how can i view my order history', 'Go to My Orders section after logging in to view all past purchases.'),
('how do i track my order', 'Open My Orders, select the order, and click Track Shipment.'),
('what payment methods do you accept', 'We accept credit cards, debit cards, UPI, and net banking.'),
('is cash on delivery available', 'Yes, cash on delivery is available for selected locations.'),
('how do i cancel my order', 'If your order has not been shipped yet, you can cancel it from My Orders.'),
('how can i return a product', 'Go to My Orders, choose the item, and click on Return Item within 7 days.'),
('when will i get my refund', 'Refunds are processed within 5 to 7 business days after the product is received.'),
('can i change my delivery address after ordering', 'Yes, contact support within 2 hours of placing the order.'),
('how long does delivery take', 'Standard delivery takes 3 to 5 business days.'),
('how do i use a coupon code', 'Enter the coupon code at checkout before making payment.'),
('my coupon code is not working', 'Check if it has expired or already been used.'),
('how do i contact customer support', 'You can email support@example.com or call our helpline.'),
('what are your customer support hours', 'Support is available from 9 AM to 9 PM, Monday to Saturday.'),
('can i place an order without creating an account', 'Yes, you can checkout as a guest but account users get better tracking.'),
('how do i update my shipping address', 'Go to Profile > Address Book to edit or add addresses.'),
('do you deliver to my location', 'Enter your pincode on the product page to check delivery availability.'),
('how can i track my shipment', 'You can track your shipment through the My Orders page.'),
('how do i change my phone number', 'Edit your phone number in Profile Settings.'),
('is my payment information secure', 'Yes, all transactions are encrypted and processed securely.'),
('can i use multiple coupons in one order', 'No, only one coupon can be applied per order.'),
('how can i check the status of my return', 'Visit My Returns under My Orders to see status updates.'),
('can i modify an order after placing it', 'No, modification is not allowed once the order is confirmed.'),
('how do i download my invoice', 'Open the order details page and click Download Invoice.'),
('how do i check product availability', 'Product availability is shown on the product page.'),
('how do i subscribe to your newsletter', 'Scroll to the bottom of the site and enter your email under Subscribe.'),
('how can i unsubscribe from emails', 'Click Unsubscribe link in any promotional email.'),
('do you ship internationally', 'Currently, we deliver only within India.'),
('is there a delivery charge', 'Orders above Rs.499 qualify for free delivery.'),
('can i reschedule my delivery', 'Contact our delivery partner through the tracking link.'),
('my order shows delivered but i did not receive it', 'Contact customer support immediately to resolve the issue.'),
('can i pay using paytm or google pay', 'Yes, both are accepted payment options.'),
('can i change my delivery slot', 'You can modify it using the link sent via SMS before dispatch.'),
('how do i report a damaged item', 'Click on Return/Replace under My Orders and upload item photos.'),
('will i get a replacement for damaged products', 'Yes, replacements are available for eligible items.'),
('how can i know if my order is confirmed', 'You will receive a confirmation email and SMS after placing the order.'),
('what happens if i am not available during delivery', 'Delivery will be reattempted twice before being returned to the warehouse.'),
('can i request express delivery', 'Yes, express delivery is available for select cities.'),
('how do i apply for a refund', 'Go to My Orders and choose Request Refund.'),
('how do i check wallet balance', 'Wallet balance is shown in your profile dashboard.'),
('how can i add money to wallet', 'Go to Wallet section and choose Add Money.'),
('what is the wallet refund policy', 'Refunds to wallet are processed instantly.'),
('can i transfer wallet balance to bank', 'No, wallet balance can only be used for future purchases.'),
('can i share my coupon with someone else', 'Coupons are account-specific and non-transferable.'),
('how can i rate a product', 'After delivery, go to the order page and click on Rate Product.'),
('how can i write a review', 'Use the Write Review button on the product page.'),
('do you have a mobile app', 'Yes, our app is available on Android and iOS.'),
('how do i download your app', 'Search for our name on Google Play Store or Apple App Store.'),
('how can i update the app', 'Go to the app store and click Update if available.'),
('why is the app crashing', 'Try clearing app cache or reinstalling the app.'),
('how do i enable notifications', 'Allow notifications in the app settings.'),
('how can i disable push notifications', 'Turn off notifications in your device settings.'),
('how do i change language in app', 'Go to App Settings and select Language Preference.'),
('how do i reset app settings', 'Clear app data from your device settings.'),
('do you offer membership benefits', 'Yes, members get free delivery and early access to sales.'),
('how can i join membership', 'Go to Membership page and click Join Now.'),
('how do i cancel membership', 'Contact support to cancel your membership plan.'),
('how do i check membership validity', 'Your expiry date is visible in the Membership section.'),
('what are reward points', 'Reward points are earned with each order and can be redeemed later.'),
('how can i redeem reward points', 'Use them at checkout to get discounts.'),
('do reward points expire', 'Yes, they expire after 12 months of inactivity.'),
('can i use both coupon and reward points', 'No, you can use either one per order.'),
('how do i contact delivery partner', 'Click the Track Shipment link for contact details.'),
('can i change payment method after order', 'No, payment method cannot be changed after placing the order.'),
('is gst included in prices', 'Yes, all prices are inclusive of GST.'),
('can i get a gst invoice', 'Yes, enter GST details at checkout to receive a tax invoice.'),
('how do i check product warranty', 'Warranty details are listed on the product page.'),
('how do i claim warranty', 'Contact the manufacturer using the details in your invoice.'),
('do you provide installation services', 'Yes, installation is available for selected electronic items.'),
('how do i schedule installation', 'You will receive a call after delivery to schedule it.'),
('can i contact the seller directly', 'No, all communication is through our platform support.'),
('what should i do if i received wrong product', 'Raise a replacement request from My Orders.'),
('can i cancel replacement request', 'Yes, you can cancel it before processing.'),
('how do i use filters on website', 'Click on Filters and choose categories, price range, and rating.'),
('how can i sort products', 'Use the Sort By dropdown to order by price or popularity.'),
('can i save products for later', 'Yes, click Add to Wishlist to save them.'),
('how do i view my wishlist', 'Go to My Wishlist section in your profile.'),
('how can i remove items from wishlist', 'Click the remove icon beside the item name.'),
('how can i share a product link', 'Click on Share button on the product page.'),
('how do i search for a product', 'Use the search bar at the top and type product name.'),
('how do i change profile picture', 'Go to Profile and upload a new image.'),
('can i link my social media account', 'Yes, link Facebook or Google from settings.'),
('how do i log out', 'Click on your profile icon and choose Logout.'),
('why am i not receiving emails', 'Check your spam folder or verify your email address.'),
('how do i contact technical support', 'Email techsupport@example.com with issue details.'),
('how do i report a bug', 'Use the Report Issue form in the Help section.'),
('can i request new product feature', 'Yes, submit your suggestion using Feedback form.'),
('is there any referral program', 'Yes, invite friends to earn referral rewards.'),
('how can i view referral rewards', 'Check My Rewards in your account.'),
('can i withdraw referral earnings', 'No, referral earnings are used as credits.'),
('how do i delete saved cards', 'Go to Payment Settings and delete the card.'),
('how do i add new card', 'Add new card details at checkout or in Payment Settings.'),
('how do i change default payment method', 'Set default card in Payment Preferences.'),
('can i contact support via chat', 'Yes, live chat is available on our Help page.'),
('can i email my feedback', 'Yes, send your feedback to feedback@example.com.'),
('how can i check order cancellation policy', 'Check Terms & Conditions under Help section.'),
('what if website is not loading', 'Clear your browser cache or try again later.'),
('how do i update my address during checkout', 'You can edit it directly on the checkout page.'),
('why was my payment declined', 'Check your card limit or contact your bank.'),
('how do i check transaction history', 'Go to Payment History in your account.'),
('can i download my transaction history', 'Yes, use the Export option in Payment History.'),
('how do i verify my email', 'Click the verification link sent to your email after signup.'),
('how can i reactivate my account', 'Login again and verify your email to reactivate.'),
('do you keep my personal data safe', 'Yes, we comply with all data protection regulations.'),
('how can i delete my browsing history', 'Use Clear History option in your profile settings.');
